import { base64 } from './intake-ai.mjs';

const escape = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]);
const listHtml = values => values.length ? `<ul>${values.map(value => `<li>${escape(value)}</li>`).join('')}</ul>` : '<p>None clearly visible.</p>';
export function buildReviewEmail(env, row, assessment, attachments) {
  const labels = { likely_accept: ['#347854', 'Likely yes'], likely_decline: ['#b34c3a', 'Likely no'], needs_review: ['#b88a24', 'Needs review'] };
  const title = `Web Submission #${row.id} - ${row.name} - ${row.photo_count} Photos`;
  const summary = assessment ? `AI found approximately ${assessment.approximate_item_count} items` : 'AI assessment unavailable — manual review needed';
  const items = assessment?.items || [];
  const itemRows = items.map(item => {
    const [color, label] = labels[item.recommendation];
    return `<tr><td style="vertical-align:top;padding:16px 10px;border-bottom:1px solid #dedfd5;white-space:nowrap"><span style="color:${color};font-size:20px">●</span> ${label}</td><td style="vertical-align:top;padding:16px 10px;border-bottom:1px solid #dedfd5"><strong>${escape(item.item)}</strong><p>${escape(item.category)}</p><p>Brand: ${escape(item.likely_brand)}</p><p>Photos ${item.photo_numbers.join(', ')}</p></td><td style="vertical-align:top;padding:16px 10px;border-bottom:1px solid #dedfd5"><p>${escape(item.assessment)}</p><p><strong>Visible condition:</strong> ${escape(item.visible_condition)}</p><strong>Visible flaws</strong>${listHtml(item.obvious_flaws)}${item.information_needed.length ? `<strong>Still needed</strong>${listHtml(item.information_needed)}` : ''}</td></tr>`;
  }).join('');
  const reply = assessment?.suggested_response || 'Thanks for sharing your photos with Changing Places. We’ll look over your items and get in touch about the next step.';
  const photos = attachments.map((attachment, index) => `<div style="display:inline-block;vertical-align:top;width:46%;padding:1%;margin:0 0 14px"><p><strong>Photo ${index + 1}</strong></p><img src="cid:${attachment.contentId}" width="320" alt="Photo ${index + 1}" style="width:100%;height:auto;border-radius:4px" /></div>`).join('');
  const html = `<html><body style="margin:0;background:#f7f5ef;color:#303a30;font:14px/1.6 Arial,sans-serif"><div style="max-width:900px;margin:24px auto;padding:28px;background:#fffefa"><p style="color:#6f785e;font-size:11px;letter-spacing:2px">CHANGING PLACES · PRIVATE CONSIGNMENT REVIEW</p><h1 style="font:26px/1.3 Georgia,serif;color:#294e43">${escape(title)}</h1><p><strong>Contact:</strong> ${escape(row.phone || 'No phone provided')} · ${escape(row.email || 'No email provided')}</p>${row.notes ? `<p><strong>Customer notes:</strong><br />${escape(row.notes).replace(/\n/g, '<br />')}</p>` : ''}<div style="padding:20px;background:#edf1e5"><h2 style="margin:0;font:22px Georgia,serif">${escape(summary)}</h2><p>${escape(assessment?.overview || 'All photos are attached below. Please assess these items directly.')}</p>${assessment?.grouping_uncertainty ? `<p>${escape(assessment.grouping_uncertainty)}</p>` : ''}</div><p><span style="color:#347854">●</span> Likely yes &nbsp; <span style="color:#b88a24">●</span> Needs review &nbsp; <span style="color:#b34c3a">●</span> Likely no</p>${items.length ? `<table style="width:100%;border-collapse:collapse;font-size:13px"><thead><tr><th align="left">Fit</th><th align="left">Item</th><th align="left">AI assessment</th></tr></thead><tbody>${itemRows}</tbody></table>` : ''}${assessment?.information_needed.length ? `<h2>Information/photos still needed</h2>${listHtml(assessment.information_needed)}` : ''}<h2 style="font:22px Georgia,serif">Suggested response to the customer</h2><p style="color:#746e61">Draft only — review and edit before sending.</p><div style="padding:20px;border:1px solid #d8ddcf">${escape(reply).replace(/\n/g, '<br />')}</div><p style="font-size:12px;color:#6b705f">AI may miss flaws or misidentify items. Staff make the final acceptance decision. No reply or decision has been sent to the customer.</p><h2 style="font:22px Georgia,serif">${row.photo_count} submitted photos</h2><p>Numbered photos are included in this email.</p>${photos}<p style="font-size:11px;color:#6b705f">Private business review. Stored web submissions are removed after 90 days; this email remains in your mailbox.</p></div></body></html>`;
  const text = `${title}\n\nPhone: ${row.phone || 'Not provided'}\nEmail: ${row.email || 'Not provided'}\nNotes: ${row.notes || 'None'}\n\n${summary}\n${assessment?.overview || 'Review the attached photos manually.'}\n${assessment?.grouping_uncertainty || ''}\n\n${items.map(item => `${labels[item.recommendation][1]} — ${item.item}\nCategory: ${item.category}\nBrand: ${item.likely_brand}\nPhotos: ${item.photo_numbers.join(', ')}\nAssessment: ${item.assessment}\nVisible condition: ${item.visible_condition}\nFlaws: ${item.obvious_flaws.join('; ') || 'None clearly visible'}\nStill needed: ${item.information_needed.join('; ') || 'No additional details flagged'}`).join('\n\n')}\n\nInformation/photos still needed: ${assessment?.information_needed.join('; ') || 'Review photos directly'}\n\nSuggested customer response (DRAFT — edit before sending):\n${reply}\n\nAI recommendations are preliminary. Staff make final decisions. All ${row.photo_count} numbered photos are attached. No customer response has been sent automatically.`;
  return { from: env.INTAKE_EMAIL_FROM, to: env.INTAKE_NOTIFICATION_EMAIL, subject: title, ...(row.email ? { replyTo: row.email } : {}), html, text, attachments };
}

export async function sendReviewEmail(env, row, assessment) {
  const attachments = [];
  for (let ordinal = 1; ordinal <= row.photo_count; ordinal++) {
    const photo = await env.INTAKE_PHOTOS.get(`${row.upload_id}/${ordinal}-email.jpg`);
    if (!photo || photo.size > 100000) throw new Error('email_photo_unavailable');
    attachments.push({ content: base64(new Uint8Array(await photo.arrayBuffer())), filename: `submission-${row.id}-photo-${String(ordinal).padStart(2, '0')}.jpg`, type: 'image/jpeg', disposition: 'inline', contentId: `photo-${ordinal}@changing-places` });
  }
  await env.INTAKE_EMAIL.send(buildReviewEmail(env, row, assessment, attachments));
}
